services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: workshop
    volumes:
      - mongo_data:/data/db

  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:root@mongo:27017/workshop?authSource=admin
    restart: always

volumes:
  mongo_data: